### PR TITLE
Add flake build

### PR DESCRIPTION
**Pull request by wraithm**

### CODE REVIEW

**Review by cdepillabout — APPROVED** [review]
This LGTM, although you might want to add an example of the `nix run` command to the top of the `flake.nix` file so that people see what they can do with it.

**Comment by wraithm** [comment]
```nix run github:bitnomial/aws-ec2-knownhosts/clf-add-flakiness```

or maybe even ```nix run github:bitnomial/aws-ec2-knownhosts```

**Comment by wraithm** [comment]
@clintonford-btnl Would you mind adding that sort of documentation in a follow up PR?

**Comment by clintonford-btnl** [comment]
> @clintonford-btnl Would you mind adding that sort of documentation in a follow up PR?

@wraithm done: https://github.com/bitnomial/aws-ec2-knownhosts/pull/17

**Comment by clintonford-btnl** [comment]
> `nix run github:bitnomial/aws-ec2-knownhosts/clf-add-flakiness`
> 
> or maybe even `nix run github:bitnomial/aws-ec2-knownhosts`

@wraithm to clarify: the `/clf-add-flakiness` suffix was to point to that branch: it's an unfortunate use of `/` as a separator IMHO but that's the HTTP API.

**Pull request merged**
